const API = 'http://localhost:8000/api';
const isPages = location.hostname.endsWith('.github.io');
if (isPages) { message.textContent = 'Vista pública: el backend local y las cámaras IP no están disponibles desde GitHub Pages.'; document.querySelector('#camera-form').querySelector('button').disabled = true; }
const grid = document.querySelector('#camera-grid');
const count = document.querySelector('#count');
const message = document.querySelector('#message');
async function request(path, options) { const response = await fetch(API + path, options); if (!response.ok) { const error = await response.json().catch(() => ({})); throw new Error(error.detail || 'Error de conexión'); } return response.json(); }
async function refresh() { try { const cameras = await request('/cameras'); count.textContent = cameras.length + ' cámaras'; grid.replaceChildren(); cameras.forEach(camera => { const card = document.createElement('article'); card.className = 'camera'; const title = document.createElement('h3'); title.textContent = camera.name; const preview = document.createElement('img'); preview.className = 'camera-feed'; preview.alt = 'Vista de ' + camera.name; preview.loading = 'lazy'; const placeholder = document.createElement('div'); placeholder.className = 'placeholder'; placeholder.textContent = 'Vista previa no iniciada'; const url = document.createElement('p'); url.textContent = camera.url; const start = document.createElement('button'); start.textContent = 'Iniciar vista MJPEG'; start.onclick = () => { if (!camera.url.startsWith('http://')) { message.textContent = 'La vista del navegador solo admite HTTP MJPEG. RTSP requiere servidor de video.'; return; } preview.src = camera.url; preview.style.display = 'block'; placeholder.style.display = 'none'; }; preview.onerror = () => { preview.removeAttribute('src'); preview.style.display = 'none'; placeholder.style.display = 'grid'; placeholder.textContent = 'No se pudo abrir el video. Comprueba IP, puerto y formato MJPEG.'; }; const remove = document.createElement('button'); remove.textContent = 'Eliminar'; remove.onclick = async () => { try { preview.removeAttribute('src'); await request('/cameras/' + camera.id, {method:'DELETE'}); await refresh(); } catch(e) { message.textContent = e.message; } }; card.append(title,placeholder,preview,url,start,remove); grid.append(card); }); } catch(e) { message.textContent = 'No se pudo conectar al backend: ' + e.message; } }
document.querySelector('#camera-form').addEventListener('submit', async event => { event.preventDefault(); const form = event.currentTarget; const data = Object.fromEntries(new FormData(form)); try { await request('/cameras', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}); form.reset(); message.textContent = 'Cámara registrada'; await refresh(); } catch(e) { message.textContent = e.message; } });
if (!isPages) refresh();
