const $ = id => document.getElementById(id);
let apiKey = '', map, markers, cameras = [], detections = [], modelReady = false;
let advisoryCache = [], previousAlertIds = new Set(), alertBootstrapped = false;
let locationMarker = null, locationAccuracy = null, locationWatchId = null, followLocation = false;

const message = (s) => { $('message').textContent = s; };
function setCameraAuth(connected){const status=$('camera-auth-status');if(status)status.textContent=connected?'Sesión conectada: ya puedes registrar cámaras.':'Sesión no conectada: introduce tu API Key arriba y pulsa Conectar antes de registrar cámaras.';const button=document.querySelector('#camera-form button[type="submit"]');if(button){button.disabled=!connected;button.title=connected?'Registrar cámara':'Conecta primero tu sesión operativa';}}
const escape = (s) => String(s ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const api = async (path, options={}) => {
  const response = await fetch('/api'+path,{...options,headers:{'X-API-Key':apiKey,...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})},cache:'no-store'});
  if(!response.ok) {let info;try{info=await response.json()}catch{};throw new Error(typeof info?.detail==='string'?info.detail:'HTTP '+response.status)}
  return response.headers.get('content-type')?.includes('application/json') ? response.json() : response;
};
function setConnection(label,ok=false){$('connection').textContent=(ok?'● ':'○ ')+label;$('connection').className='status '+(ok?'ok':'warn');}
function initMap(){if(!window.L){$('map').textContent='Mapa no disponible: no se pudo cargar el proveedor.';return;}map=L.map('map',{scrollWheelZoom:false,preferCanvas:true}).setView([-9.93,-76.24],7);markers=L.layerGroup().addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap contributors'}).addTo(map);const resize=()=>{if(!map)return;map.invalidateSize({pan:false,animate:false});};const stableResize=()=>{requestAnimationFrame(()=>{resize();setTimeout(resize,200);});};map.whenReady(stableResize);setTimeout(stableResize,250);setTimeout(stableResize,900);setTimeout(stableResize,2000);window.addEventListener('resize',resize);if(window.ResizeObserver){let lastWidth=0,lastHeight=0;const observer=new ResizeObserver(entries=>{const rect=entries[0].contentRect;if(Math.abs(rect.width-lastWidth)<1&&Math.abs(rect.height-lastHeight)<1)return;lastWidth=rect.width;lastHeight=rect.height;stableResize();});observer.observe($('map'));}document.querySelectorAll('a[href="#map-panel"]').forEach(link=>link.addEventListener('click',()=>setTimeout(resize,350)));}
function getCoordinates(camera){const lat=Number(camera.lat??camera.latitude),lng=Number(camera.lng??camera.longitude);return Number.isFinite(lat)&&Number.isFinite(lng)&&Math.abs(lat)<=90&&Math.abs(lng)<=180&&(camera.lat!=null||camera.latitude!=null)&&(camera.lng!=null||camera.longitude!=null)?[lat,lng]:null;}
function renderMap(){if(!map)return;markers.clearLayers();const bounds=[];for(const camera of cameras){const coord=getCoordinates(camera);if(!coord)continue;const events=detections.filter(d=>String(d.camera_id)===String(camera.id));const latest=events[0];const popup=document.createElement('div');popup.textContent=camera.name+' · '+(latest?latest.label+' · '+Math.round(Number(latest.confidence)*100)+'%':'Sin detecciones');L.circleMarker(coord,{radius:9,color:latest?'#f59e7a':'#36d3e3',fillOpacity:.7}).addTo(markers).bindPopup(popup);bounds.push(coord);}if(bounds.length&&!followLocation)map.fitBounds(bounds,{padding:[35,35],maxZoom:13});setTimeout(()=>map.invalidateSize({pan:false,animate:false}),120);$('map-note').textContent=bounds.length?'Cámaras georreferenciadas: '+bounds.length+'. Las probabilidades provienen del modelo.':'Ninguna cámara tiene coordenadas verificadas. El mapa conserva la vista regional sin inventar puntos.';}
function stopLocationTracking(){if(locationWatchId!==null&&navigator.geolocation){navigator.geolocation.clearWatch(locationWatchId);}locationWatchId=null;followLocation=false;const button=$('locate-me');button.textContent='◎ Mi ubicación';button.setAttribute('aria-pressed','false');if(locationMarker){map.removeLayer(locationMarker);locationMarker=null;}if(locationAccuracy){map.removeLayer(locationAccuracy);locationAccuracy=null;}}
function locateMe(){if(!map){message('Mapa no disponible.');return;}if(locationWatchId!==null){stopLocationTracking();message('Seguimiento de ubicación desactivado.');return;}if(!window.isSecureContext||!navigator.geolocation){message('La ubicación requiere HTTPS y un navegador compatible.');return;}const button=$('locate-me');button.textContent='Buscando ubicación…';button.disabled=true;const onSuccess=position=>{button.disabled=false;const {latitude,longitude,accuracy}=position.coords;if(!Number.isFinite(latitude)||!Number.isFinite(longitude))return;const coord=[latitude,longitude];if(!locationMarker){locationMarker=L.circleMarker(coord,{radius:9,color:'#ffffff',weight:3,fillColor:'#22d3ee',fillOpacity:1}).addTo(map).bindPopup('Tu ubicación aproximada');}else locationMarker.setLatLng(coord);if(!locationAccuracy){locationAccuracy=L.circle(coord,{radius:accuracy,color:'#22d3ee',weight:1,fillOpacity:.08}).addTo(map);}else locationAccuracy.setLatLng(coord).setRadius(accuracy);if(followLocation){map.invalidateSize({pan:false});map.setView(coord,Math.max(map.getZoom(),15),{animate:false});}button.textContent='◉ Ubicación activa';button.setAttribute('aria-pressed','true');$('map-note').textContent='Ubicación aproximada obtenida con tu permiso (precisión estimada: '+Math.round(accuracy)+' m). Solo se usa en este navegador.';};const onError=error=>{button.disabled=false;stopLocationTracking();const reason=error.code===1?'Permiso de ubicación denegado. Actívalo en los ajustes del navegador.':error.code===2?'No se pudo determinar tu posición. Revisa GPS o señal.':'La solicitud de ubicación tardó demasiado.';message(reason);};followLocation=true;locationWatchId=navigator.geolocation.watchPosition(onSuccess,onError,{enableHighAccuracy:true,maximumAge:10000,timeout:20000});}
$('locate-me').addEventListener('click',locateMe);
$('map-reset').addEventListener('click',()=>{stopLocationTracking();if(!map)return;map.invalidateSize({pan:false});map.setView([-9.93,-76.24],7);renderMap();message('Vista regional restaurada.');});

async function loadSnapshot(camera, card){const state=card.querySelector('.camera-state');const view=card.querySelector('.feed');state.textContent='Solicitando imagen al servidor…';try{const response=await api('/cameras/'+encodeURIComponent(camera.id)+'/snapshot');const blob=await response.blob();if(!blob.type.startsWith('image/'))throw Error('Respuesta no es imagen');const old=view.querySelector('img');if(old){URL.revokeObjectURL(old.src);old.remove()}const img=document.createElement('img');img.className='camera-frame';img.alt='Captura actual de '+camera.name;img.src=URL.createObjectURL(blob);view.append(img);state.textContent='Cámara accesible: imagen recibida del servidor. Pulsa Ver cámara IP para actualizar.';}catch(e){state.textContent='Servidor sin acceso a la cámara: '+e.message+'. Puedes probar la vista directa si estás en la misma Wi-Fi; en HTTPS el navegador puede bloquear HTTP.';}}
function openLocalCamera(camera, card){
  const state=card.querySelector('.camera-state'), view=card.querySelector('.feed');
  let url;
  try { url=new URL(camera.url); } catch { state.textContent='URL de cámara inválida.'; return; }
  if(!['http:','https:'].includes(url.protocol)){state.textContent='La vista local del navegador requiere HTTP/MJPEG o HTTPS/MJPEG; RTSP necesita un puente de video.';return;}
  if(location.protocol==='https:' && url.protocol==='http:'){
    state.textContent='Vista directa bloqueada: el dashboard usa HTTPS y la cámara HTTP privada. Abre la dirección de la cámara en una pestaña desde la misma Wi-Fi para comprobarla. Para integrarla aquí necesitas un puente HTTPS seguro o ejecutar NEXUS localmente.';
    return;
  }
  const old=view.querySelector('img');if(old)old.remove();
  const img=document.createElement('img');img.className='camera-frame';img.alt='Vista directa de '+camera.name;
  img.referrerPolicy='no-referrer';img.style.width='100%';img.style.height='100%';img.style.objectFit='contain';
  img.onload=()=>{state.textContent='Imagen recibida directamente por el navegador. Esto no confirma conexión del servidor ni análisis IA.';};
  img.onerror=()=>{img.remove();state.textContent='No se pudo abrir la transmisión local. Comprueba que ambos dispositivos estén en la misma red, la URL MJPEG y los permisos del navegador.';};
  img.src=url.href;view.append(img);state.textContent='Intentando conexión directa desde este navegador…';
}
async function refreshPushedFrames(){
  if(!apiKey)return;
  for(const card of document.querySelectorAll('#camera-grid .camera')){
    const id=card.dataset.cameraId;
    if(!id)continue;
    try{
      const response=await api('/cameras/'+encodeURIComponent(id)+'/frame');
      const blob=await response.blob();
      if(!blob.type.startsWith('image/'))continue;
      const view=card.querySelector('.feed');
      const old=view.querySelector('img');
      const image=document.createElement('img');image.className='camera-frame';
      image.alt='Último fotograma recibido del agente local';
      image.src=URL.createObjectURL(blob);
      image.onload=()=>{if(old){if(old.src.startsWith('blob:'))URL.revokeObjectURL(old.src);old.remove()}};
      view.append(image);
      card.querySelector('.camera-state').textContent='Agente local conectado · imagen actualizada ('+new Date().toLocaleTimeString('es-PE')+'). Actualización de fotogramas, no video continuo.';
    }catch(e){
      if(!card.querySelector('.feed img'))card.querySelector('.camera-state').textContent='Cámara registrada. Sin imágenes del agente local; ejecuta scripts/start_camera_bridge.ps1 en tu PC.';
    }
  }
}
function renderCameras(){const grid=$('camera-grid');grid.replaceChildren();$('camera-capacity').textContent=cameras.length+' cámaras registradas · admite 6 o más';if(!cameras.length){grid.innerHTML='<div class="empty">No hay cámaras IP registradas. Añade la primera para iniciar el monitoreo.</div>';return;}for(const camera of cameras){const card=document.createElement('article');card.className='camera';card.dataset.cameraId=String(camera.id);const latest=detections.find(d=>String(d.camera_id)===String(camera.id));const confidence=latest&&Number.isFinite(Number(latest.confidence))?(Number(latest.confidence)*100).toFixed(1)+'%':'—';card.innerHTML='<div class="feed"><span class="feed-icon">▣</span><span class="feed-label">FUENTE IP · VIDEO BAJO AUTORIZACIÓN</span></div><div class="camera-info"><h3>'+escape(camera.name)+'</h3><p>'+escape(latest?latest.label+' · confianza '+confidence:'Sin detecciones registradas')+'</p><div class="camera-actions"><button class="snapshot outline">Ver cámara IP</button><button class="local-preview outline">Vista local</button><button class="detect">Analizar IA</button><button class="remove outline">Eliminar</button></div><small class="camera-state">No se afirma transmisión hasta verificar el flujo.</small></div>';card.querySelector('.snapshot').onclick=()=>loadSnapshot(camera,card);card.querySelector('.local-preview').onclick=()=>openLocalCamera(camera,card);card.querySelector('.detect').onclick=async()=>{const state=card.querySelector('.camera-state');state.textContent='Analizando…';try{const result=await api('/cameras/'+encodeURIComponent(camera.id)+'/detect',{method:'POST'});state.textContent=result.status==='ok'?'Análisis completado.':'Sin inferencia: '+(result.status||'modelo no disponible');await loadData();}catch(e){state.textContent='Error: '+e.message}};card.querySelector('.remove').onclick=async()=>{if(!confirm('¿Eliminar esta cámara?'))return;try{await api('/cameras/'+encodeURIComponent(camera.id),{method:'DELETE'});await loadData()}catch(e){message('No se pudo eliminar: '+e.message)}};grid.append(card);}}
function renderEvents(){const body=$('event-rows');body.replaceChildren();if(!detections.length){body.innerHTML='<tr><td colspan="5">Sin detecciones reales registradas</td></tr>';return;}for(const d of detections.slice(0,100)){const tr=document.createElement('tr');const cam=cameras.find(c=>String(c.id)===String(d.camera_id));const confidence=Number(d.confidence);const date=d.created_at||d.timestamp;const cols=[date?new Date(date).toLocaleString('es-PE'):'—',cam?.name||d.camera_id||'—',d.label||'—',Number.isFinite(confidence)?(confidence*100).toFixed(1)+'%':'—',d.review_status||'—'];for(const val of cols){const td=document.createElement('td');td.textContent=String(val);tr.append(td)}body.append(tr)}}
function renderAdvisories(items){advisoryCache=items;const filter=$('alert-filter').value;const shown=filter==='all'?items:items.filter(x=>x.review_status===filter);$('alert-count').textContent=shown.length+' señales visibles · '+items.length+' registradas';const pending=items.filter(x=>x.review_status==='pending_human_review');const banner=$('alert-strip');banner.className='alert-strip '+(pending.length?'alert-active':items.length?'alert-observed':'');$('alert-headline').textContent=pending.length?'⚠ '+pending.length+' SEÑALES PENDIENTES DE REVISIÓN':items.length?'SEÑALES REGISTRADAS · REVISAR HISTORIAL':'CENTRO DE ALERTAS · SIN SEÑALES REGISTRADAS';$('alert-summary').textContent=pending.length?'Se requiere validación humana. No son pronósticos de desastres.':items.length?'Hay registros de fenómenos; consulta su estado antes de tomar decisiones.':'Sin señales registradas. Esto no garantiza ausencia de riesgos.';if(alertBootstrapped&&pending.length&&Notification.permission==='granted'){for(const item of pending){if(!previousAlertIds.has(item.detection_id)){new Notification('NEXUS · Señal para revisión',{body:item.phenomenon+': '+item.message,tag:item.detection_id});}}}previousAlertIds=new Set(pending.map(x=>x.detection_id));alertBootstrapped=true;const root=$('advisory-list');root.replaceChildren();if(!shown.length){const p=document.createElement('p');p.className='help';p.textContent='Sin señales de riesgo registradas. La ausencia de detecciones no garantiza ausencia de peligro.';root.append(p);return;}for(const item of shown.slice(0,12)){const el=document.createElement('article');el.className='advisory';const h=document.createElement('strong');h.textContent=item.phenomenon+' · '+(Number(item.confidence)*100).toFixed(1)+'% de confianza del clasificador';const p=document.createElement('p');p.textContent=item.message;const small=document.createElement('small');small.textContent='Cámara '+item.camera_id+' · '+(item.review_status||'sin revisar')+' · No es pronóstico meteorológico';el.append(h,p,small);if(item.review_status==='pending_human_review'){const actions=document.createElement('div');actions.className='review-actions';for(const [label,decision] of [['✓ Confirmar','confirmed'],['× Descartar','dismissed']]){const button=document.createElement('button');button.textContent=label;button.className=decision==='dismissed'?'outline':'';button.onclick=async()=>{if(!confirm('¿Registrar decisión humana: '+label+'?'))return;try{await api('/detections/'+encodeURIComponent(item.detection_id)+'/review',{method:'PATCH',body:JSON.stringify({decision,notes:'Revisión manual desde el centro de operaciones'})});await loadData()}catch(e){message('No se pudo revisar: '+e.message)}};actions.append(button)}el.append(actions)}root.append(el);}}
function renderChart(stats){const chart=$('chart');chart.replaceChildren();const items=Object.entries(stats.by_label||{}).sort((a,b)=>b[1]-a[1]);if(!items.length){chart.innerHTML='<p class="help">Todavía no hay detecciones registradas.</p>';return;}const max=Math.max(1,...items.map(x=>x[1]));for(const [label,n] of items){const row=document.createElement('div');row.className='bar-row';const name=document.createElement('span');name.textContent=label;const track=document.createElement('div');track.className='track';const bar=document.createElement('i');bar.style.width=(n/max*100)+'%';track.append(bar);const count=document.createElement('strong');count.textContent=n;row.append(name,track,count);chart.append(row)}}
async function loadData(){if(!apiKey)return;try{const [cams,events,stats,model,advisories]=await Promise.all([api('/cameras'),api('/detections?limit=100'),api('/stats'),api('/model/status'),api('/risk-advisories')]);cameras=Array.isArray(cams)?cams:[];detections=Array.isArray(events)?events:[];modelReady=Boolean(model.ready);$('count-cameras').textContent=cameras.length;$('count-detections').textContent=stats.detections_total??detections.length;$('count-pending').textContent=stats.pending_review??0;$('model-ready').textContent=modelReady?'LISTO':'NO DISPONIBLE';$('model-ready').className='model-state '+(modelReady?'ready':'offline');$('model-detail').textContent=modelReady?'Modelo cargado; resultados sujetos a revisión':'Modelo no instalado. Consulta README.md para habilitar la detección.';renderCameras();refreshPushedFrames();renderEvents();renderAdvisories(advisories);renderChart(stats);renderMap();$('last-update').textContent='Sincronizado '+new Date().toLocaleTimeString('es-PE');setConnection('API conectada',true);setCameraAuth(true);message(modelReady?'API conectada · Modelo de IA operativo.':'API conectada correctamente · Dashboard disponible.');}catch(e){setConnection('Acceso no disponible');setCameraAuth(false);message('No se pudieron cargar datos operativos: '+e.message+'. Verifica la API Key en Sesión operativa.');}}
$('connect').onclick=()=>{apiKey=$('api-key').value.trim();$('api-key').value='';if(!apiKey){setCameraAuth(false);message('Introduce una clave de API válida.');return;}$('auth-note').textContent='Clave mantenida en memoria durante esta pestaña; no se guarda en el navegador.';loadData()};
$('camera-form').onsubmit=async e=>{e.preventDefault();if(!apiKey){message('Primero introduce la clave NEXUS_API_KEY en Sesión operativa y pulsa Conectar.');document.getElementById('api-key').focus();return;}const name=$('camera-name').value.trim(),url=$('camera-url').value.trim();const latText=$('camera-latitude').value.trim(),lonText=$('camera-longitude').value.trim();if(Boolean(latText)!==Boolean(lonText)){message('Introduce ambas coordenadas o deja ambas vacías.');return;}const latitude=latText?Number(latText):null,longitude=lonText?Number(lonText):null;if(/^https?:\/\/192\.168\.|^https?:\/\/10\.|^https?:\/\/172\.(1[6-9]|2[0-9]|3[01])\./.test(url)){message('Atención: la IP privada '+url+' no es accesible desde Railway. Para ver tu teléfono usa un servidor local en la misma Wi-Fi o una conexión VPN segura. El registro no confirma transmisión.');}try{const created=await api('/cameras',{method:'POST',body:JSON.stringify({name,url,latitude,longitude})});e.target.reset();await loadData();message('Cámara «'+name+'» registrada correctamente (ID: '+created.id+'). Para visualizar imágenes en Railway, inicia el agente local en tu computadora.');document.getElementById('cameras').scrollIntoView({behavior:'smooth',block:'start'});}catch(err){message('No se pudo registrar cámara: '+err.message);$('camera-name').focus()}};
$('refresh').onclick=loadData;
$('alert-filter').onchange=()=>renderAdvisories(advisoryCache);
$('enable-notifications').onclick=async()=>{if(!('Notification' in window)){message('Este navegador no admite notificaciones.');return;}if(!window.isSecureContext){message('Las notificaciones requieren HTTPS.');return;}const permission=await Notification.requestPermission();message(permission==='granted'?'Avisos activados para nuevas señales pendientes mientras la página esté abierta.':'El navegador no concedió permiso de notificaciones.');};
$('pdf-report').onclick=async e=>{e.preventDefault();if(!apiKey){message('Conecta la API primero.');return;}try{const response=await api('/reports/detections.pdf');const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='nexus-reporte-detecciones.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}catch(err){message('No se pudo exportar: '+err.message)}};
const tick=()=>{$('clock').textContent=new Date().toLocaleString('es-PE')};tick();setInterval(tick,30000);initMap();setCameraAuth(false);
fetch('/health',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);setConnection('Servidor en línea',true);message('Servidor en línea. Introduce tu clave de API para consultar datos reales.')}).catch(()=>{setConnection('Servidor desconectado');message('No se pudo conectar con el backend.')});
setInterval(()=>{if(apiKey)loadData()},30000);

setInterval(refreshPushedFrames,3000);
